### ISSUE TITLE
Elastic search borks

### ISSUE THREAD

**Issue by gerroon** [zammad/zammad-docker-compose#102]
Hi
I clone the repo and trying to run docker-compose up but it seems like the elastic search one is pooping

```
zammad-postgresql_1     | LOG:  invalid record length at 0/2D30180: wanted 24, got 0                                                                                                         
zammad-postgresql_1     | LOG:  redo is not required                                                                                                                                         
zammad-postgresql_1     | LOG:  MultiXact member wraparound protections are now enabled                                                                                                      
zammad-postgresql_1     | LOG:  database system is ready to accept connections                                                                                                               
zammad-postgresql_1     | LOG:  autovacuum launcher started                                                                                                                                  
zammad-postgresql_1     | LOG:  incomplete startup packet                                                                                                                                    
zammad-elasticsearch_1  | [2019-04-04T03:22:38,889][INFO ][o.e.n.Node               ] [] initializing ...                                                                                    
zammad-elasticsearch_1  | [2019-04-04T03:22:38,921][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]                                               
zammad-elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment                                                   
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
zammad-elasticsearch_1  |       at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       ... 6 more
zammad-elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
zammad-elasticsearch_1  |       at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
zammad-elasticsearch_1  |       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
zammad-elasticsearch_1  |       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
zammad-elasticsearch_1  |       at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
zammad-elasticsearch_1  |       at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_191]
zammad-elasticsearch_1  |       at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_191]
zammad-elasticsearch_1  |       at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_191]
zammad-elasticsearch_1  |       at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:225) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.14.jar:5.6.14]
zammad-elasticsearch_1  |       ... 6 more
zammad-docker-compose_zammad-elasticsearch_1 exited with code 1
``

**Comment by gerroon** [comment]
folder permission I think
