### ISSUE TITLE
"Unable to process GET request to elasticsearch" error on init

### ISSUE THREAD

**Issue by regisb** [zammad/zammad-docker-compose#118]
### Infos:

* Docker version: `Docker version 19.03.1, build 74b1e89`
* Docker-compose version: `docker-compose version 1.23.2, build 1110ad0`
* Operating system (Docker host): Debian 9.9 (Stretch)
* .env file on the host:

```
$ cat .env
# don't forget to add the minus before the version
# example: VERSION=-2.9.0-1
IMAGE_REPO=zammad/zammad-docker-compose
VERSION=
RESTART=unless-stopped
```

### Expected behavior:

`docker-compose up` should properly initialise the Elasticsearch database.

### Actual behavior:

When running `docker-compose up`, the `zammad-init` container complains that it cannot reach the Elasticsearch container. 

### Steps to reproduce the behavior:

I managed to reproduce the issue by running bash into the container:

    docker-compose run --rm --entrypoint=bash zammad-init

Then, launch the init script:

    /docker-entrypoint.sh zammad-init

```
root@a304789881b2:/opt/zammad# /docker-entrypoint.sh zammad-init
initialising / updating database...
changing settings...
I, [2019-09-30T13:01:05.436199 #21-46952730101180]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "KnowledgeBase::Answer::Translation", "User",
 "Ticket", "Organization"])
I, [2019-09-30T13:01:07.626358 #21-46952730101180]  INFO -- : Setting.set('es_url', "http://zammad-elasticsearch:9200")
zammad railsserver waiting for elasticsearch server to be ready...
zammad railsserver waiting for elasticsearch server to be ready... 
zammad railsserver waiting for elasticsearch server to be ready...          
rebuilding es searchindex...                                                  
I, [2019-09-30T13:01:38.241712 #34-47197992887740]  INFO -- : Setting.set('models_searchable', ["Chat::Session", "KnowledgeBase::Answer::Translation", "User",
 "Ticket", "Organization"])                  
drop indexes...I, [2019-09-30T13:01:39.243020 #34-47197992887740]  INFO -- : # curl -X GET "http://zammad-elasticsearch:9200"
I, [2019-09-30T13:01:39.297802 #34-47197992887740]  INFO -- : # 0
E, [2019-09-30T13:01:39.298224 #34-47197992887740] ERROR -- : Unable to process GET request to elasticsearch URL 'http://zammad-elasticsearch:9200'. Elasticse
arch is not reachable, probably because it's not running or even installed.

Response:
#<UserAgent::Result:0x000055da4f937e28 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP con
nection to zammad-elasticsearch:9200 (Connection refused - connect(2) for \"zammad-elasticsearch\" port 9200)>">

Payload:
nil

Payload size: 0M
rake aborted!
Unable to process GET request to elasticsearch URL 'http://zammad-elasticsearch:9200'. Elasticsearch is not reachable, probably because it's not running or even installed.

Response:
#<UserAgent::Result:0x000055da4f937e28 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP con
nection to zammad-elasticsearch:9200 (Connection refused - connect(2) for \"zammad-elasticsearch\" port 9200)>">

Payload:
nil

Payload size: 0M
rake aborted!
Unable to process GET request to elasticsearch URL 'http://zammad-elasticsearch:9200'. Elasticsearch is not reachable, probably because it's not running or even installed.

Response:
#<UserAgent::Result:0x000055da4f937e28 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to zammad-elasticsearch:9200 (Connection refused - connect(2) for \"zammad-elasticsearch\" port 9200)>">

Payload:
nil

Payload size: 0M
/opt/zammad/lib/search_index_backend.rb:43:in `info'
/opt/zammad/lib/tasks/search_index_es.rake:278:in `es_version'
/opt/zammad/lib/tasks/search_index_es.rake:298:in `es_multi_index?'
/opt/zammad/lib/tasks/search_index_es.rake:9:in `block (2 levels) in <main>'
/opt/zammad/lib/tasks/search_index_es.rake:151:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)
```

As suggested by the stacktrace, I did try to obtain the full trace by running:

    bundle exec rake searchindex:rebuild --trace

Here is the corresponding stacktrace:

```
/opt/zammad/lib/search_index_backend.rb:43:in `info'                                                  
/opt/zammad/lib/tasks/search_index_es.rake:278:in `es_version'                       
/opt/zammad/lib/tasks/search_index_es.rake:298:in `es_multi_index?'
/opt/zammad/lib/tasks/search_index_es.rake:9:in `block (2 levels) in <main>'           
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'                        
/opt/zammad/lib/tasks/search_index_es.rake:151:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'          
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => searchindex:rebuild
```

Note that the elasticsearch container is running and reachable from the zammad-init container, as I could verify with:

```
root@a304789881b2:/opt/zammad# curl -X GET http://zammad-elasticsearch:9200
{
  "name" : "ho6KJba",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "Tbf6b_F5QcSpxVRL78nx0w",
  "version" : {
    "number" : "5.6.14",
    "build_hash" : "f310fe9",
    "build_date" : "2018-12-05T21:20:16.416Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by venkat330** [comment]
Any update on this?
