### ISSUE TITLE
Lost File Storage during container Crash - What can I DO?

### ISSUE THREAD

**Issue by diegodorgam** [zammad/zammad-docker-compose#19]
Hey guys, having some trouble with Zammad Docker-Compose version in rancher.

I've tried to create custom fields in Object ticket, and some error ocurred, I couldn't catch the log, but I tried then to restart the railsserver container and the role server stopped, so I reinitiated the server and everything comes up again, but railsserver is failing to start, here is the log output:

```
13/05/2017 15:24:35railsserver can access postgresql server now...
13/05/2017 15:24:39/home/zammad/app/models/store/provider/file.rb:32:in `get': ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371 (RuntimeError)
13/05/2017 15:24:39	from /home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:39	from /home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:39	from /home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:39	from /home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:39	from /home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:39	from /home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:39	from /home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:52:in `<top (required)>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
13/05/2017 15:24:39	from bin/rails:4:in `require'
13/05/2017 15:24:39	from bin/rails:4:in `<main>'
13/05/2017 15:24:43creating db & searchindex...
13/05/2017 15:24:46zammad_production already exists
13/05/2017 15:24:50rake aborted!
13/05/2017 15:24:50ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:24:50/home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:24:50/home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:50/home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:50/home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:50/home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:50/home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:50/home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:50/home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
13/05/2017 15:24:50/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
13/05/2017 15:24:50/usr/local/bin/bundle:22:in `load'
13/05/2017 15:24:50/usr/local/bin/bundle:22:in `<main>'
13/05/2017 15:24:50Tasks: TOP => db:migrate => environment
13/05/2017 15:24:50(See full trace by running task with --trace)
13/05/2017 15:24:53rake aborted!
13/05/2017 15:24:53ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:24:53/home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:24:53/home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:53/home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:53/home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:53/home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:53/home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:53/home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:53/home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
13/05/2017 15:24:53/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:182:in `block (2 levels) in <top (required)>'
13/05/2017 15:24:53/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
13/05/2017 15:24:53/usr/local/bin/bundle:22:in `load'
13/05/2017 15:24:53/usr/local/bin/bundle:22:in `<main>'
13/05/2017 15:24:53Tasks: TOP => db:abort_if_pending_migrations => environment
13/05/2017 15:24:53(See full trace by running task with --trace)
13/05/2017 15:24:57rake aborted!
13/05/2017 15:24:57ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:24:57/home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:24:57/home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:57/home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:57/home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:57/home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:57/home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:57/home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:57/home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
13/05/2017 15:24:57/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
13/05/2017 15:24:57/usr/local/bin/bundle:22:in `load'
13/05/2017 15:24:57/usr/local/bin/bundle:22:in `<main>'
13/05/2017 15:24:57Tasks: TOP => searchindex:rebuild => environment
13/05/2017 15:24:57(See full trace by running task with --trace)
13/05/2017 15:24:57starting zammad...
13/05/2017 15:24:57zammad will be accessable on http://localhost in some seconds
13/05/2017 15:24:58Puma starting in single mode...
13/05/2017 15:24:58* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
13/05/2017 15:24:58* Min threads: 5, max threads: 30
13/05/2017 15:24:58* Environment: production
13/05/2017 15:25:01! Unable to load application: RuntimeError: ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:25:01bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
13/05/2017 15:25:01RuntimeError: ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:25:01  /home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:25:01  /home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:25:01  /home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:25:01  /home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:25:01  /home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:25:01  /home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:25:01  /home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:25:01  /home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:25:01  config.ru:3:in `require'
13/05/2017 15:25:01  config.ru:3:in `block in <main>'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
13/05/2017 15:25:01  config.ru:in `new'
13/05/2017 15:25:01  config.ru:in `<main>'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
13/05/2017 15:25:01  /usr/local/bundle/bin/puma:17:in `load'
13/05/2017 15:25:01  /usr/local/bundle/bin/puma:17:in `<top (required)>'
```

after those logs, railsserver container just stops.. Any Ideas?
I still have a postgresql zammad_production sql DUMP to restore. But it seems that it loosed some files stored in the container. There's any way to get my instance working back again?

**Comment by diegodorgam** [comment]
This is how the stored_files tables looks like:
```
zammad_production=# select * from store_files;
 id  |                               sha                                | provider |         created_at         |       updated_at
-----+------------------------------------------------------------------+----------+----------------------------+-------------------------
   1 | 4b48f88a5a30fce63d4af89ffb2a2562ecb8e4701a8ea58ace386d7058fd00cb | DB       | 2017-04-13 22:12:58.781967 | 2017-04-13 22:12:58.781
   5 | 1547e363d03199e0296bd1215b9aa01c9001c12ea711cc8687698f0956c970b2 | DB       | 2017-04-13 22:19:58.972642 | 2017-04-13 22:19:58.972
   6 | d4a4bd24f2bb2d1027d8e2c4da5d547ea829eef41c14a2680d5dbf60c7426f62 | DB       | 2017-04-13 22:19:58.988283 | 2017-04-13 22:19:58.988
   7 | e6baf5e8bf0bc16d34c80ab75067d4c5345b2d472064b1e7bcac96e57d1f84c8 | DB       | 2017-04-13 22:19:59.532892 | 2017-04-13 22:19:59.532
   8 | 32062c6106e2338917e1b8de42ad3dd9e9da1deaa6cdab330e443dc53a91eae0 | DB       | 2017-04-13 22:19:59.543862 | 2017-04-13 22:19:59.543
   9 | 09f273e1f502fc83b7120e7376e5e21f9d62233b381fd43c5d46731c9360cbd0 | DB       | 2017-04-13 22:20:00.109106 | 2017-04-13 22:20:00.109
  10 | b3d05572d10fbdad7b9d69daf4dc79c7c14adced57a2d2ff466f8e8096b94a42 | DB       | 2017-04-13 22:20:00.120719 | 2017-04-13 22:20:00.12
  11 | 65d54dbf758412c549b7ed5a1869ad3dd35d4ebbe92f8f72de6927a1f6d96786 | DB       | 2017-04-13 22:28:09.568485 | 2017-04-13 22:28:09.568
  12 | 112178e5c8f85bb8f49f456ca9019a40aa28cb2ad14380eb25e19013d9536be3 | DB       | 2017-04-14 17:33:44.44891  | 2017-04-14 17:33:44.448
  13 | 383fc86705ffa542f0d8710914c4f6da1d683f808cb96bfdac6f4063d1d86d4e | DB       | 2017-04-14 17:33:44.462214 | 2017-04-14 17:33:44.462
  16 | 62c43e850826d1d5375d87b9c04368f31e3f48c57e43fb5dab77a8643e87513c | DB       | 2017-04-21 20:01:13.596159 | 2017-04-21 20:01:13.596
  17 | dc8c0f8d1e9370b28722b408548956836f5199812262f288e2b3458211a63943 | DB       | 2017-04-21 20:02:09.495991 | 2017-04-21 20:02:09.495
  18 | a5d6f8ef09d676b9617be1ffe170847b4d7d150fa5107ca9481d03eca0625b1a | DB       | 2017-04-21 20:02:09.509556 | 2017-04-21 20:02:09.509
  19 | fda5cdde5a6fe8c12d30560645208b041122cfcbb36dc391be44b51f8583e6c3 | DB       | 2017-04-21 20:02:09.52669  | 2017-04-21 20:02:09.526
  20 | 923f1f497b1949a3421179abe514e6dca53c20ec2e24e3fdf18ee11c8fadff58 | DB       | 2017-04-21 20:02:10.721254 | 2017-04-21 20:02:10.721
  21 | f215e79398029be555af4801e516052ccfbc9fb8454adf1a136da52a4eb1c994 | DB       | 2017-04-21 20:02:10.734885 | 2017-04-21 20:02:10.734
  22 | d7a1683b3277a216fb87b233785ce34917931b80af4d6b317058f0f2c6064717 | DB       | 2017-04-21 20:02:10.753134 | 2017-04-21 20:02:10.753
  29 | 90b5b8e17c8ff788345beaa868eaca91fa51d88b65cb3cb15e341e1292656584 | File     | 2017-04-22 02:55:43.668218 | 2017-04-22 02:55:43.668
  30 | 46f4bbc11a20c98d79cbd13568769d0b7a9a88643f12eb5c96b68d75a5c55371 | File     | 2017-04-22 02:55:43.701862 | 2017-04-22 02:55:43.701
  31 | 15f1102aeeda33c2cf3933c7136494cbd806a8826845874c368ef1ef3840fb01 | DB

zammad_production=# select * from store_files where provider='File';
 id |                               sha                                | provider |         created_at         |       updated_at
----+------------------------------------------------------------------+----------+----------------------------+-------------------------
 29 | 90b5b8e17c8ff788345beaa868eaca91fa51d88b65cb3cb15e341e1292656584 | File     | 2017-04-22 02:55:43.668218 | 2017-04-22 02:55:43.668
 30 | 46f4bbc11a20c98d79cbd13568769d0b7a9a88643f12eb5c96b68d75a5c55371 | File     | 2017-04-22 02:55:43.701862 | 2017-04-22 02:55:43.701
(2 rows)
```

**Comment by monotek** [comment]
@martini @thorsteneckel any glue what happened here?

**Comment by martini** [comment]
Hi @diegodorgam 

> I've tried to create custom fields in Object ticket, and some error ocurred,...

That should not be a problem. Did you change the file store backed from DB to File (at least for a short time)?

`zammad run rails r "p Setting.get('storage_provider')"`

**Comment by martini** [comment]
Any feedback?

**Comment by monotek** [comment]
Closing as no feedback given....
