### ISSUE TITLE
Fails to operate on M1 macs.

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-docker-compose#218]
# Infos

* Docker version: 20.10.7
* Docker-compose version: 1.29.2
* Operating system (Docker host): macOS 11.4 M1

# Expected behavior

* Docker images work on M1 mac platforms.

# Actual behavior

* docker-compose fails to bring up the containers into a fully working state.
* elasticsearch fails to come up: `Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/elasticsearch/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 232, exit value: 1`
* other containers run in `qemu` to emulate linux/amd64
* CPU usage at 200% with no final progress

# Steps to reproduce the behavior

* Call `docker-compose up` on a M1 mac.

Would it be possible to support [multi-arch builds](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)? At least the M1 mac platform will be an important developer platform in future, so it would be great to have support for this.

**Comment by waja** [comment]
As the images seems to be build with github actions [docker-buildx](https://github.com/marketplace/actions/docker-buildx#quick-start) might be an option to build also for arm. The question is: Is Java (and depending software) running on ARM? Starting point might be https://alexmanrique.com/blog/development/2021/01/05/first-steps-using-java-in-macbook-air-m1.html.

**Comment by mgruner** [comment]
The used elasticsearch image is available: https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss:7.10.2 (arm64 and amd64).

**Comment by monotek** [comment]
Imho running Zammad on a macbook with ARM is not the usecase of this repo and supporting that setup creates unneeded maintenace work.

**Comment by mgruner** [comment]
- Operating on a M1 Mac Server seems to be a valid use case, even if they are not available just yet.
- External developers and/or Zammad employees (like myself) who are tasked with supporting this repository might have M1 development platforms.

**Comment by monotek** [comment]
We don't have an m1 server userbase. 
We should talk about it, if we get one but i don see this in the near future and therefore investing time to run on m1 mac makes no sense to me. 

I would even doubt that a supportcase is a valid point here because "works on my m1" might not mean anything for the default linux user group.

**Comment by Nitair** [comment]
I'm also interested in M1 compatibility. 

_Why?_ 
I would like to host it locally in order to develop integrations BEFORE running the system on production or anywhere else

**Comment by mgruner** [comment]
Ping

**Comment by odidev** [comment]
I am also interested on using the zammad on linux/arm64 platform. I have tried building it on my arm64 server but facing below errors:
```
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect'
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:4:in `<main>'
/usr/local/bundle/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `require'
/tmp/zammad-stable/config/application.rb:20:in `block in <top (required)>'
/tmp/zammad-stable/config/application.rb:19:in `select'
/tmp/zammad-stable/config/application.rb:19:in `<top (required)>'
/tmp/zammad-stable/Rakefile:7:in `require_relative'
/tmp/zammad-stable/Rakefile:7:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:478:in `exec'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
(See full trace by running task with –trace)
```
I have just updated base image to ruby:2.7.4-slim as I was getting issue with 2.6.8-slim version. Could you please provide me pointers to resolve the same to build for ARM64?

If interested, I will do required changes and raise PR.

**Comment by MrGeneration** [comment]
@odidev no offense but that's a technical question. Please check the documentation and it's dependencies especially if you're (seems like) running in parallel to the compose builds.

https://docs.zammad.org/en/latest/prerequisites/software.html#node-js

**Comment by mgruner** [comment]
There will be [arm64 support with Zammad 6.2 containers](https://github.com/zammad/zammad/commit/8cd3c221e358fee0f2efadcee705acbb5f9ffc3e).
