### ISSUE TITLE
Railsserver broken

### ISSUE THREAD

**Issue by xf-** [zammad/zammad-docker-compose#22]
### Infos:

* Docker version: newest
* Docker-compose version: newest
* Operating system (Docker host): arch

### Expected behavior:

* Working railsserver

### Actual behavior:

* Container is broken

```
zammad-railsserver_1    | Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
zammad-railsserver_1    | starting zammad...
zammad-railsserver_1    | zammad will be accessable on http://localhost in some seconds
zammad-railsserver_1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
zammad-railsserver_1    | Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

Endless loop
```

### Steps to reproduce the behavior:

* Load newest build

**Comment by monotek** [comment]
Can't reproduce.

**Comment by xf-** [comment]
I updated a working instance and docker container is a complete ruby environment - no influence from from my OS.

I updated the container just now and it still crashes:
```
zammad-railsserver_1    | railsserver can access postgresql server now...
zammad-postgresql_1     | LOG:  incomplete startup packet
zammad-scheduler_1      | scheduler waiting for zammads railsserver to be ready...
zammad-railsserver_1    | bundler: failed to load command: rails (/usr/local/bundle/bin/rails)
zammad-railsserver_1    | Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    | creating db & searchindex...
zammad-railsserver_1    | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
zammad-railsserver_1    | Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    | Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
zammad-railsserver_1    | bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
```

@monotek  Any idea how to fix this or debug it? The container instant crashes, no way to access it.

**Comment by monotek** [comment]
I also could no reproduce any update problem. No problems using:
* docker-compose stop
* docker-compose pull
* docker-compose start

**Comment by xf-** [comment]
It wont work, recreating won't6 solve the issue.
Creating a new folder with same containers works (git repo is untouched).

Any way to create a backup and restore it or other solution to get existing instance back? The stops after starting it.

**Comment by monotek** [comment]
You could docker exec in the postgres container and do at least a db backup which should enable you to restore zammad somewhere else.

**Comment by Braintelligence** [comment]
Same issue

**Comment by Braintelligence** [comment]
@xf- Did you find a workaround for this? What steps did you take to recreate a working environment?

**Comment by Braintelligence** [comment]
Could this be related?
https://github.com/bundler/bundler/issues/5068#issuecomment-297983093

**Comment by gpkvt** [comment]
I have the same issue with 1.15:

`zammad-railsserver_1    | starting zammad...
zammad-railsserver_1    | zammad will be accessable on http://localhost in some seconds
zammad-railsserver_1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
zammad-railsserver_1    | Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
zammad-railsserver_1    |   /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
zammad-railsserver_1    |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
`

**Comment by gpkvt** [comment]
It works fine if I delete the volume for zammaddockercompose_data-zammad. But then I have to setup a new system.

**Comment by Braintelligence** [comment]
Well, I turned it off for now and hope for a different solution than setting up a new system...

**Comment by gpkvt** [comment]
The new setup seems to be a result of deleting all containers and images which was needed in order to delete the volume. When the new containers are created they seem to use new volumes. You should check in which volume the postgres-container saves it data before the removal. Afterwards you can just copy the files from the old to the new volume (postgres-container must be stopped when doing so).

**Comment by mraerino** [comment]
We can reproduce this over here.
Seems to be connected to the fact, that the `data-zammad` volume is bound at `/home/zammad` and therefore also may persist the `Gemfile[.lock]`
Is there a way we can attach one (or several) volumes located deeper in `/home/zammad` so the Gemfile is always taken from the image?

For solving this, we need to answer these questions:
- Where are attachments stored if you chose `Filesystem` as a storage option for it?
- Which files need to be shared between some containers?

**Comment by monotek** [comment]
Yes, that's pretty much the problem. Unfortunately I had no time to fix it.
Fix could be to update the container via git.
But need to build new image for that as git us deinstalled at the moment.

**Comment by t3easy** [comment]
You could start a 2nd zammad server, mount the data volume to another folder and copy the files from /home/zammad over to the mounted data-zammad folder

**Comment by t3easy** [comment]
If you copy the whole /home/zammad, yes. Maybe backup all files before.
(I'm new to zammad but use docker some time now)

**Comment by Braintelligence** [comment]
So database files and everything is contained there, as well. Alright, I'll try it soon. Thanks :).

**Comment by monotek** [comment]
Refactored everything. Should work now.
Don't forget to git pull this repo before.
Please reopen if still a problem.

**Comment by Braintelligence** [comment]
After upgrading all containers in rancher I now get this in the railsserver logs:

´HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>´

**Comment by monotek** [comment]
This is just the request which checks if the railsserver port is open. You can ignore it.

**Comment by Braintelligence** [comment]
I managed to get the railsserver running but I get this on websocket:
```
30.7.2017 17:40:32websocket server can access raillsserver now...
30.7.2017 17:40:32bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)
30.7.2017 17:40:32Bundler::GemNotFound: Your bundle is locked to mini_portile2 (2.1.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mini_portile2 (2.1.0) has removed it. You'll need to update your bundle to a different version of mini_portile2 (2.1.0) that hasn't been removed in order to install.
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
30.7.2017 17:40:32  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
30.7.2017 17:40:32  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
30.7.2017 17:40:32  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by Braintelligence** [comment]
Upgraded every container with the new tags, adding a `-29` behind the old tag, just to make 100% sure I'm using the newest images.
Still the same problem.

**Comment by monotek** [comment]
Please execute:
* docker-compose stop
* git pull
* docker-compose pull 
* docker-compose start

Post the output of all commands.

**Comment by Braintelligence** [comment]
@monotek 
I'm not sure how to do this in a rancher environment.

**Comment by monotek** [comment]
Somit in the shell.
