### ISSUE TITLE
Proper way to restore using zammad-docker-compose

### ISSUE THREAD

**Issue by nemhods** [zammad/zammad-docker-compose#222]
# Infos

* Docker version: 20.10.7
* Docker-compose version: 1.26.0
* Operating system (Docker host): Ubuntu 20.04

# Expected behavior

* the  script /opt/zammad/contrib/backup/zammad_restore.sh works

# Actual behavior

Afaik, It's not really documented where and how to run a restore from. So I tried a few different approaches which are all not working.

## Running from zammad-railsserver
```
docker-compose exec zammad-railsserver bash
cd /opt/zammad/contrib/backup
./zammad_restore.sh
```

```
# Zammad restored started - Sun Jul 18 08:55:12 UTC 2021!

# Stopping Zammad
zammad: unrecognized service
# Restoring Files
# Ensuring correct file rights ...
# Checking requirements
# ... Dropping current database zammad_production
/usr/bin/env: ‘ruby’: No such file or directory
# ... Creating database zammad_production for owner zammad
/usr/bin/env: ‘ruby’: No such file or directory
# Restoring PostgrSQL DB
Password: su: Authentication failure
# Clearing Cache ...
/usr/bin/env: ‘ruby’: No such file or directory
# Starting Zammad
zammad: unrecognized service

# Zammad restored successfully - Sun Jul 18 08:55:17 UTC 2021!
```

## Running from zammad-backup (which is the postgresql container)

```
docker-compose exec zammad-backup bash
cd /opt/zammad/contrib/backup
./zammad_restore.sh
```

```
# Zammad restored started - Sun Jul 18 08:42:46 UTC 2021!

# Stopping Zammad
/opt/zammad/contrib/backup/functions: line 132: service: command not found
# Restoring Files
# Ensuring correct file rights ...
chown: unknown user/group zammad:zammad
# Checking requirements
# ERROR: User 'zammad' is not present, but should be by default! #
# Restoration was NOT successful, exiting ...
```

... here I tried adding the user manually, but then I get similar errors like in the above container (psql missing, ruby missing).

I've tried adding ruby by `apk add ruby`, but then I get into dependency problems:
```
Traceback (most recent call last):
        4: from /opt/zammad/bin/rails:8:in `<main>'
        3: from /opt/zammad/bin/rails:8:in `require_relative'
        2: from /opt/zammad/config/boot.rb:3:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- bundler/setup (LoadError)
```

It seems like the containers are not yet set up do allow users to restore from backup. What's the correct way to restore in a docker-compose scenario?

**Comment by stefangweichinger** [comment]
@nemhods did you find out how to restore in a docker-compose environment? I might have to do that soon while migrating the stack to a new docker host. thanks
