### ISSUE TITLE
memory usage from elasticsearch

### ISSUE THREAD

**Issue by cyberrranger** [zammad/zammad-docker-compose#264]
# Infos

* Docker version: Docker version 18.09.7, build 2d0083d
* Docker-compose version: docker-compose version 1.29.2, build 5becea4c
* Operating system (Docker host): Ubuntu

# Expected behavior

* Not that much memory usage

# Actual behavior

* AFTER starting a new installation, 32GB of memory will be used from the system
* if the system memory 40GB i cant start 2 diffent docker-compose zammad system, the second system write an error in the log

> zammad-elasticsearch_1  | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
> zammad-elasticsearch_1  | output:
> zammad-elasticsearch_1  | #
> zammad-elasticsearch_1  | # There is insufficient memory for the Java Runtime Environment to continue.
> zammad-elasticsearch_1  | # Native memory allocation (mmap) failed to map 33285996544 bytes for committing reserved memory.
> zammad-elasticsearch_1  | # An error report file with more information is saved as:
> zammad-elasticsearch_1  | # logs/hs_err_pid188.log
> zammad-elasticsearch_1  | error:
> zammad-elasticsearch_1  | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000001001000000, 33285996544, 0) failed; error='Not enough space' (errno=12)
> zammad-elasticsearch_1  | 	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
> zammad-elasticsearch_1  | 	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
> zammad-elasticsearch_1  | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
> zammad-elasticsearch_1  | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
> zammad-elasticsearch_1  | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)

# Steps to reproduce the behavior

* git clone 
* docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.prod.yml up -d

**Comment by cyberrranger** [comment]
i see #256 , the same problem
