### ISSUE TITLE
scheduler and websocket reboot in loop after restart

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#36]
### Infos:

* Docker version: 17.06
* Docker-compose version: 1.15.0
* Operating system (Docker host): Ubuntu 16.04

### Expected behavior:

* All services start normally after host reboot

### Actual behavior:

* scheduler and websocket reboot in loop
```
websocket server can access raillsserver now...
bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)
Bundler::GemNotFound: Your bundle is locked to clearbit (0.2.7), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of clearbit (0.2.7) has removed it. You'll need to update your bundle to a different version of clearbit (0.2.7) that hasn't been removed in order to install.
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
```
scheduler can access raillsserver now...
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
Bundler::GemNotFound: Your bundle is locked to clearbit (0.2.7), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of clearbit (0.2.7) has removed it. You'll need to update your bundle to a different version of clearbit (0.2.7) that hasn't been removed in order to install.
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

### Steps to reproduce the behavior:

* Restart the host

**Comment by t3easy** [comment]
Was a problem with docker registry and an outdated image.

**Comment by martini** [comment]
Thanks for feedback! :)
