### ISSUE TITLE
Containers do not start up correctly after a system restart

### ISSUE THREAD

**Issue by Berdir** [zammad/zammad-docker-compose#60]
### Infos:

* Docker version 17.09.1-ce, build 19e2cf6
* Docker-compose version:
* Operating system (Docker host): Debian stretch

### Expected behavior:

Zammad is accessible after restarting the system.

### Actual behavior:

Haven't been able to track down exactly what the problem is, but basically I get an nginx error and the site doesn't respond.

When I then run docker-compose restart, everything works fine. It seems like the containers aren't starting in the correct order or something like that.

I don't have a lot of experience with docker, so not sure where to start debugging this.

### Steps to reproduce the behavior:

*

**Comment by monotek** [comment]
Whats the nginx error?

Please do:
* docker-compose stop
* git pull
* docker-compose pull
* docker-compose up

**Comment by Berdir** [comment]
Actually the error is from the ngnix reverse proxy that is running on another system, looks like the port isn't up at all (I changed the port mapping to "8000:80"):

curl http://localhost:8000
curl: (56) Recv failure: Connection reset by peer

But the nginx container is running:
074469c25154        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 29 seconds       0.0.0.0:8000->80/tcp   zammad_zammad-nginx_1

docker-compose logs zammad-nginx reports a lot of lines like this at the end:
zammad-nginx_1          | waiting for all zammad services to start...
zammad-nginx_1          | waiting for all zammad services to start...

zammad-railsserver is logging this in a loop:
zammad-railsserver_1    | waiting for install or update to be ready...
zammad-railsserver_1    | waiting for install or update to be ready...

**Comment by Berdir** [comment]
And I'm on the latest version, but stop and up again will obviously fix the problem, just like restart. But I don't want to have to start it manually in case the system is restarted for whatever reason.

Thanks for the very quick feedback!

**Comment by monotek** [comment]
Was any of the containers stopped or restarted separately?

Whats the output of:
* docker ps

**Comment by Berdir** [comment]
docker ps looked like this:

```
# docker-compose ps
            Name                           Command               State           Ports         
----------------------------------------------------------------------------------------------
zammad_zammad-backup_1          /usr/local/bin/backup.sh z ...   Up       5432/tcp             
zammad_zammad-elasticsearch_1   /bin/bash bin/es-docker          Up       9200/tcp, 9300/tcp   
zammad_zammad-init_1            /docker-entrypoint.sh zamm ...   Exit 0                        
zammad_zammad-memcached_1       /docker-entrypoint.sh zamm ...   Up       11211/tcp            
zammad_zammad-nginx_1           /docker-entrypoint.sh zamm ...   Up       0.0.0.0:8000->80/tcp 
zammad_zammad-postgresql_1      docker-entrypoint.sh postgres    Up       5432/tcp             
zammad_zammad-railsserver_1     /docker-entrypoint.sh zamm ...   Up                            
zammad_zammad-scheduler_1       /docker-entrypoint.sh zamm ...   Up                            
zammad_zammad-websocket_1       /docker-entrypoint.sh zamm ...   Up      
```
so the only thing that wasn't reported as Up is the init container. But that is the same after docker-compose restart.

No, all containers were running normally and for a while when I restarted, with "init 6".

**Comment by monotek** [comment]
I've asked for docker ps. I cant see what i wanted to see.

**Comment by Berdir** [comment]
Ah sorry. reading is hard :)

```
# docker ps
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS              PORTS                  NAMES
074469c25154        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 5 minutes        0.0.0.0:8000->80/tcp   zammad_zammad-nginx_1
692c97d55225        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 5 minutes                               zammad_zammad-websocket_1
63810cd96106        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 5 minutes                               zammad_zammad-scheduler_1
aed22aed5170        zammad/zammad-docker-compose:zammad-postgresql      "/usr/local/bin/ba..."   2 days ago          Up 5 minutes        5432/tcp               zammad_zammad-backup_1
687da0449e31        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 5 minutes                               zammad_zammad-railsserver_1
f35070763c47        zammad/zammad-docker-compose:zammad-elasticsearch   "/bin/bash bin/es-..."   2 days ago          Up 5 minutes        9200/tcp, 9300/tcp     zammad_zammad-elasticsearch_1
d0d3f218f031        zammad/zammad-docker-compose:zammad-memcached       "/docker-entrypoin..."   2 days ago          Up 5 minutes        11211/tcp              zammad_zammad-memcached_1
97007c5e44e4        zammad/zammad-docker-compose:zammad-postgresql      "docker-entrypoint..."   2 days ago          Up 5 minutes        5432/tcp               zammad_zammad-postgresql_1
```

That is from before I restarted.

This is the output now, after I restarted a while ago:

```
# docker ps
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS              PORTS                  NAMES
074469c25154        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 26 minutes       0.0.0.0:8000->80/tcp   zammad_zammad-nginx_1
692c97d55225        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 26 minutes                              zammad_zammad-websocket_1
63810cd96106        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 26 minutes                              zammad_zammad-scheduler_1
aed22aed5170        zammad/zammad-docker-compose:zammad-postgresql      "/usr/local/bin/ba..."   2 days ago          Up 26 minutes       5432/tcp               zammad_zammad-backup_1
687da0449e31        zammad/zammad-docker-compose:zammad                 "/docker-entrypoin..."   2 days ago          Up 26 minutes                              zammad_zammad-railsserver_1
f35070763c47        zammad/zammad-docker-compose:zammad-elasticsearch   "/bin/bash bin/es-..."   2 days ago          Up 26 minutes       9200/tcp, 9300/tcp     zammad_zammad-elasticsearch_1
d0d3f218f031        zammad/zammad-docker-compose:zammad-memcached       "/docker-entrypoin..."   2 days ago          Up 26 minutes       11211/tcp              zammad_zammad-memcached_1
97007c5e44e4        zammad/zammad-docker-compose:zammad-postgresql      "docker-entrypoint..."   2 days ago          Up 26 minutes       5432/tcp               zammad_zammad-postgresql_1
```

I can't see a difference there.

**Comment by monotek** [comment]
Could you please try again with current version?

**Comment by Berdir** [comment]
Trying, but having trouble updating, getting the following exception from elasticsearch container:

```
zammad-elasticsearch_1  | 4) Error injecting constructor, java.lang.IllegalStateException: unable to upgrade the mappings for the index [[zammad_production/gn_d008ORkKNrTHMHEmUSg]]
zammad-elasticsearch_1  |   at org.elasticsearch.gateway.GatewayMetaState.<init>(Unknown Source)
zammad-elasticsearch_1  |   while locating org.elasticsearch.gateway.GatewayMetaState
zammad-elasticsearch_1  | Caused by: java.lang.IllegalStateException: unable to upgrade the mappings for the index [[zammad_production/gn_d008ORkKNrTHMHEmUSg]]
zammad-elasticsearch_1  | 	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:172)
zammad-elasticsearch_1  | 	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:98)
zammad-elasticsearch_1  | 	at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:249)
zammad-elasticsearch_1  | 	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:93)
zammad-elasticsearch_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
zammad-elasticsearch_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
zammad-elasticsearch_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
zammad-elasticsearch_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:176)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42)
zammad-elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:499)
zammad-elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:245)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
zammad-elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
zammad-elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
zammad-elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
zammad-elasticsearch_1  | Caused by: MapperParsingException[Failed to parse mapping [Ticket]: No handler for type [attachment] declared on field [attachment]]; nested: MapperParsingException[No handler for type [attachment] declared on field [attachment]];
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:332)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:285)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:264)
zammad-elasticsearch_1  | 	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:168)
zammad-elasticsearch_1  | 	... 37 more
zammad-elasticsearch_1  | Caused by: MapperParsingException[No handler for type [attachment] declared on field [attachment]]
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:273)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:199)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parse(ObjectMapper.java:173)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:277)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:199)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:102)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:111)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:91)
zammad-elasticsearch_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:329)
zammad-elasticsearch_1  | 	... 40 more
zammad-elasticsearch_1  | 
zammad-elasticsearch_1  | 4 errors
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:361) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:164) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.5.jar:5.6.5]
zammad-elasticsearch_1  | 	... 6 more
```

**Comment by Berdir** [comment]
https://github.com/zammad/zammad/issues/1037 seems to be related to that error, but I don't know how I'm supposed to fix that when using containers.

**Comment by Berdir** [comment]
I see, https://github.com/zammad/zammad-docker-compose/commit/c224217da414f03b6e0a8d5c467fc794dc56a05f changed the mapper plugin, but somhow updating doesn't work?

**Comment by Berdir** [comment]
Got it working again by deleting the elasticsearch volume and then restarting. That's not very nice but a different problem.

I seem to get further now but I have a different problem. Looks like restarting the system keeps the pid file around of the railsserver, I'm getting this error now in the logs after a restart:

zammad-railsserver_1    | A server is already running. Check /opt/zammad/tmp/pids/server.pid.

deleting it manually on the running container then makes that happy and lets it continue.

Possibly the pid file should be on an actual tmp file system that is not part of the persisted value, so that it won't exist after a system restart? A docker container doesn't really need a pid file I think anyway? But I guess the problem is also that this file isn't removed/the container is not stopped properly on a system shutdown?

**Comment by monotek** [comment]
The pid file should be removed by the rsync command in the entrypoint.sh init script: https://github.com/zammad/zammad-docker-compose/blob/6888a87abd8a10e232fe15a33f7389dc6423571e/containers/zammad/docker-entrypoint.sh#L26

**Comment by Berdir** [comment]
Trying to debug this further, found out something new. I think the reason that it's not working for me is that the zammad-init container isn't executed for me on a restart, probably because that one was not running when the docker service is stopped as it is set to restart policy "on-failure". 

I searched a bit, but none of the restart policies seem to make sense here, seems like I would need the opposite of "unless-stopped", to only start it on a docker/system restart.

I feel like I'm missing something obvious here but couldn't see anything in the documentation that would apply to this?

**Comment by monotek** [comment]
"on-failure" is correct. 
It means the container is started once, when run without error or restarted when has failure.

**Comment by monotek** [comment]
I guess this happens because your server is rebooted without stopping zammad gracefully before?
Please do "docker-compose stop" before you reboot the server.

**Comment by devel0** [comment]
### Infos:

* Used Zammad version: zammd-docker-compose ( b568b6782a122136dda0c8c9f48e275a5054279d @Mon Feb 5 20:20:23 2018 +0100 )
* Installation method (source, package, ..): git working copy docker compose
* Operating system: linux ubuntu 16.04
* Database + version: 
* Elasticsearch version:
* Browser + version:


### Expected behavior:

* container restart successful


### Actual behavior:

* railsserver fail to restart

```
starting railsserver...
A server is already running. Check /opt/zammad/tmp/pids/server.pid.
=> Booting Puma
=> Rails 5.1.4 application starting in production 
=> Run `rails server -h` for more startup options
Exiting
starting railsserver...
A server is already running. Check /opt/zammad/tmp/pids/server.pid.
=> Booting Puma
=> Rails 5.1.4 application starting in production 
=> Run `rails server -h` for more startup options
Exiting
```

### Steps to reproduce the behavior:

* not sure what the cause, may a docker pause all container and docker unpause all containers

### Workaround

To avoid restart loop of the container should enough to remove stale pid file before to start the railsserver container ( I think would correct to remove the pid in the entrypoint to allow a restart auto-cleanup ).
In my case I remove the file outside container with following

```
rm -f /var/lib/docker/volumes/zammaddockercompose_zammad-data/_data/tmp/pids/server.pid
```

**Comment by JannikZed** [comment]
And this is really the answer to this problem?? Gracefully stopping all containers and/or manually deleting the PID file? What happens in an unexpected shutdown of the service? We have zammad running in kubernetes and this way we normally don't have to care about such problems any longer! But with zammad, we have so much manual work again.. thats really not a clean way of dealing with such issues..

**Comment by Anis-kabli** [comment]
Do you have any updates please ?

**Comment by MrGeneration** [comment]
Please don't hijack 5 year old, closed issues.
If you are experiencing a bug, create your own bug report on this repo with all required information.
